---

apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
      run: jnlp
      app: executors
spec:
  containers:
    - name: jnlp
      image: registry.ubuntu.home/alpine/jenkins/inbound-agent/3283.v92c105e0f819-8-alpine-jdk21:latest
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins
          name: sharedvolume
    - name: kaniko
      image: registry.ubuntu.home/gcr.io/kaniko-project/executor:v1.24.0.debug
      command:
        - /busybox/cat
      resources:
        limits:
          cpu: 400m
          memory: 8Gi
        requests:
          cpu: 400m
          memory: 8Gi
      tty: true
      volumeMounts:
        - mountPath: /home
          name: sharedvolume
  imagePullSecrets:
  - name: regcred
  volumes:
    - name: sharedvolume
      emptyDir: {}

